spring.application.name=Finance_Tracker
server.port = 8081

spring.datasource.url=jdbc:postgresql://db.gdzmkhydyrakhoozyuug.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=upduUpiDYf2bFBnY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

